version: '3'

volumes:
  sportyspots_postgres_data_local: {}
  sportyspots_postgres_backup_local: {}
  app:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    command: /start.sh
    volumes:
      - app:/app

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    depends_on:
      - django
    links:
      - django
    volumes:
      - app:/app:ro
    ports:
      - "0.0.0.0:80:80"

  redis:
    image: redis:4.0

  celeryworker:
    <<: *django
    depends_on:
     - postgres
     - redis
    command: /start-celeryworker.sh

  celerybeat:
    <<: *django
    depends_on:
      - postgres
      - redis
    command: /start-celerybeat.sh

  postgres:
    container_name: sportyspots_postgres
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    volumes:
      - sportyspots_postgres_data_local:/var/lib/postgresql/data
      - sportyspots_postgres_backup_local:/backups
    env_file:
      - ./.env
