---

# to verify ufw configuration run:
# sudo ufw status verbose
# From: https://github.com/cturner80/digital-ocean-ansible/blob/master/tasks/ufw.yml
- name: Install ufw
  apt:
    name: ufw
    state: present

- name: Enable ufw with logging
  ufw:
    state: enabled
    logging: on

- name: Configure ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - direction: "incoming"
      policy: "deny"
    - direction: "outgoing"
      policy: "allow"
  notify:
    - restart ufw

- name: Allow ssh traffic
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - rule: "limit"
      port: "{{ ssh_port | default('22') }}"
      proto: "tcp"
  notify:
    - restart_ufw

- name: Setup SSH connection rate limiting
  ufw:
    rule: limit
    port: ssh
    proto: tcp
...
