---
- name: Create dev teams users
  user:
    name: "{{ item }}"
    groups:
      - ssh-users
      - sudo
    append: yes
    shell: /bin/bash
  loop: "{{ ssh_users }}"

- name: Set authorized keys for dev team users
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', 'ssh_keys/public/' + item + '.pub') }}"
  loop: "{{ ssh_users }}"

- name: Set password less sudo for users in sudo group
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
