---
# inventory group_vars/all
hostname: dev
deploy:
  celery_workers: 1
  domain: rookie.sportyspots.com
  gunicorn_workers: 1
  loglevel: info
  type: dev
instances:
  - name: dev
    cache_url: redis:///var/run/redis/redis.sock?db=0
    celery_broker_url: redis+socket:///var/run/redis/redis.sock?virtual_host=1
    once_url: redis://localhost:6379/0
...
