# Generated by Django 2.2b1 on 2019-03-14 11:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [("wagtailcore", "0041_group_collection_permissions_verbose_name_plural")]

    operations = [
        migrations.CreateModel(
            name="PageHome",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "body",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "hero_header",
                                wagtail.core.blocks.StructBlock(
                                    [
                                        ("heading", wagtail.core.blocks.CharBlock(default="")),
                                        ("sub_heading", wagtail.core.blocks.CharBlock(default="")),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={"verbose_name": "homepage", "verbose_name_plural": "homepages"},
            bases=("wagtailcore.page",),
        )
    ]
