# Generated by Django 2.1.2 on 2019-03-29 13:43

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [("cms", "0002_create_homepage")]

    operations = [
        migrations.AlterField(
            model_name="pagehome",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "hero_header",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("heading", wagtail.core.blocks.CharBlock(default="")),
                                ("sub_heading", wagtail.core.blocks.CharBlock(default="")),
                            ]
                        ),
                    ),
                    (
                        "icon_banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-white", "white"),
                                            ("bg-lightest", "gray"),
                                            ("bg-yellow", "yellow"),
                                            ("bg-transparent", "transparent"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.core.blocks.CharBlock()),
                                ("description", wagtail.core.blocks.TextBlock()),
                                (
                                    "icon",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("lnr-home", "lnr-home"),
                                            ("lnr-apartment", "lnr-apartment"),
                                            ("lnr-pencil", "lnr-pencil"),
                                            ("lnr-magic-wand", "lnr-magic-wand"),
                                            ("lnr-drop", "lnr-drop"),
                                            ("lnr-lighter", "lnr-lighter"),
                                            ("lnr-poop", "lnr-poop"),
                                            ("lnr-sun", "lnr-sun"),
                                            ("lnr-moon", "lnr-moon"),
                                            ("lnr-cloud", "lnr-cloud"),
                                            ("lnr-cloud-upload", "lnr-cloud-upload"),
                                            ("lnr-cloud-download", "lnr-cloud-download"),
                                            ("lnr-cloud-sync", "lnr-cloud-sync"),
                                            ("lnr-cloud-check", "lnr-cloud-check"),
                                            ("lnr-database", "lnr-database"),
                                            ("lnr-lock", "lnr-lock"),
                                            ("lnr-cog", "lnr-cog"),
                                            ("lnr-trash", "lnr-trash"),
                                            ("lnr-dice", "lnr-dice"),
                                            ("lnr-heart", "lnr-heart"),
                                            ("lnr-star", "lnr-star"),
                                            ("lnr-star-half", "lnr-star-half"),
                                            ("lnr-star-empty", "lnr-star-empty"),
                                            ("lnr-flag", "lnr-flag"),
                                            ("lnr-envelope", "lnr-envelope"),
                                            ("lnr-paperclip", "lnr-paperclip"),
                                            ("lnr-inbox", "lnr-inbox"),
                                            ("lnr-eye", "lnr-eye"),
                                            ("lnr-printer", "lnr-printer"),
                                            ("lnr-file-empty", "lnr-file-empty"),
                                            ("lnr-file-add", "lnr-file-add"),
                                            ("lnr-enter", "lnr-enter"),
                                            ("lnr-exit", "lnr-exit"),
                                            ("lnr-graduation-hat", "lnr-graduation-hat"),
                                            ("lnr-license", "lnr-license"),
                                            ("lnr-music-note", "lnr-music-note"),
                                            ("lnr-film-play", "lnr-film-play"),
                                            ("lnr-camera-video", "lnr-camera-video"),
                                            ("lnr-camera", "lnr-camera"),
                                            ("lnr-picture", "lnr-picture"),
                                            ("lnr-book", "lnr-book"),
                                            ("lnr-bookmark", "lnr-bookmark"),
                                            ("lnr-user", "lnr-user"),
                                            ("lnr-users", "lnr-users"),
                                            ("lnr-shirt", "lnr-shirt"),
                                            ("lnr-store", "lnr-store"),
                                            ("lnr-cart", "lnr-cart"),
                                            ("lnr-tag", "lnr-tag"),
                                            ("lnr-phone-handset", "lnr-phone-handset"),
                                            ("lnr-phone", "lnr-phone"),
                                            ("lnr-pushpin", "lnr-pushpin"),
                                            ("lnr-map-marker", "lnr-map-marker"),
                                            ("lnr-map", "lnr-map"),
                                            ("lnr-location", "lnr-location"),
                                            ("lnr-calendar-full", "lnr-calendar-full"),
                                            ("lnr-keyboard", "lnr-keyboard"),
                                            ("lnr-spell-check", "lnr-spell-check"),
                                            ("lnr-screen", "lnr-screen"),
                                            ("lnr-smartphone", "lnr-smartphone"),
                                            ("lnr-tablet", "lnr-tablet"),
                                            ("lnr-laptop", "lnr-laptop"),
                                            ("lnr-laptop-phone", "lnr-laptop-phone"),
                                            ("lnr-power-switch", "lnr-power-switch"),
                                            ("lnr-bubble", "lnr-bubble"),
                                            ("lnr-heart-pulse", "lnr-heart-pulse"),
                                            ("lnr-construction", "lnr-construction"),
                                            ("lnr-pie-chart", "lnr-pie-chart"),
                                            ("lnr-chart-bars", "lnr-chart-bars"),
                                            ("lnr-gift", "lnr-gift"),
                                            ("lnr-diamond", "lnr-diamond"),
                                            ("lnr-linearicons", "lnr-linearicons"),
                                            ("lnr-dinner", "lnr-dinner"),
                                            ("lnr-coffee-cup", "lnr-coffee-cup"),
                                            ("lnr-leaf", "lnr-leaf"),
                                            ("lnr-paw", "lnr-paw"),
                                            ("lnr-rocket", "lnr-rocket"),
                                            ("lnr-briefcase", "lnr-briefcase"),
                                            ("lnr-bus", "lnr-bus"),
                                            ("lnr-car", "lnr-car"),
                                            ("lnr-train", "lnr-train"),
                                            ("lnr-bicycle", "lnr-bicycle"),
                                            ("lnr-wheelchair", "lnr-wheelchair"),
                                            ("lnr-select", "lnr-select"),
                                            ("lnr-earth", "lnr-earth"),
                                            ("lnr-smile", "lnr-smile"),
                                            ("lnr-sad", "lnr-sad"),
                                            ("lnr-neutral", "lnr-neutral"),
                                            ("lnr-mustache", "lnr-mustache"),
                                            ("lnr-alarm", "lnr-alarm"),
                                            ("lnr-bullhorn", "lnr-bullhorn"),
                                            ("lnr-volume-high", "lnr-volume-high"),
                                            ("lnr-volume-medium", "lnr-volume-medium"),
                                            ("lnr-volume-low", "lnr-volume-low"),
                                            ("lnr-volume", "lnr-volume"),
                                            ("lnr-mic", "lnr-mic"),
                                            ("lnr-hourglass", "lnr-hourglass"),
                                            ("lnr-undo", "lnr-undo"),
                                            ("lnr-redo", "lnr-redo"),
                                            ("lnr-sync", "lnr-sync"),
                                            ("lnr-history", "lnr-history"),
                                            ("lnr-clock", "lnr-clock"),
                                            ("lnr-download", "lnr-download"),
                                            ("lnr-upload", "lnr-upload"),
                                            ("lnr-enter-down", "lnr-enter-down"),
                                            ("lnr-exit-up", "lnr-exit-up"),
                                            ("lnr-bug", "lnr-bug"),
                                            ("lnr-code", "lnr-code"),
                                            ("lnr-link", "lnr-link"),
                                            ("lnr-unlink", "lnr-unlink"),
                                            ("lnr-thumbs-up", "lnr-thumbs-up"),
                                            ("lnr-thumbs-down", "lnr-thumbs-down"),
                                            ("lnr-magnifier", "lnr-magnifier"),
                                            ("lnr-cross", "lnr-cross"),
                                            ("lnr-menu", "lnr-menu"),
                                            ("lnr-list", "lnr-list"),
                                            ("lnr-chevron-up", "lnr-chevron-up"),
                                            ("lnr-chevron-down", "lnr-chevron-down"),
                                            ("lnr-chevron-left", "lnr-chevron-left"),
                                            ("lnr-chevron-right", "lnr-chevron-right"),
                                            ("lnr-arrow-up", "lnr-arrow-up"),
                                            ("lnr-arrow-down", "lnr-arrow-down"),
                                            ("lnr-arrow-left", "lnr-arrow-left"),
                                            ("lnr-arrow-right", "lnr-arrow-right"),
                                            ("lnr-move", "lnr-move"),
                                            ("lnr-warning", "lnr-warning"),
                                            ("lnr-question-circle", "lnr-question-circle"),
                                            ("lnr-menu-circle", "lnr-menu-circle"),
                                            ("lnr-checkmark-circle", "lnr-checkmark-circle"),
                                            ("lnr-cross-circle", "lnr-cross-circle"),
                                            ("lnr-plus-circle", "lnr-plus-circle"),
                                            ("lnr-circle-minus", "lnr-circle-minus"),
                                            ("lnr-arrow-up-circle", "lnr-arrow-up-circle"),
                                            ("lnr-arrow-down-circle", "lnr-arrow-down-circle"),
                                            ("lnr-arrow-left-circle", "lnr-arrow-left-circle"),
                                            ("lnr-arrow-right-circle", "lnr-arrow-right-circle"),
                                            ("lnr-chevron-up-circle", "lnr-chevron-up-circle"),
                                            ("lnr-chevron-down-circle", "lnr-chevron-down-circle"),
                                            ("lnr-chevron-left-circle", "lnr-chevron-left-circle"),
                                            ("lnr-chevron-right-circle", "lnr-chevron-right-circle"),
                                            ("lnr-crop", "lnr-crop"),
                                            ("lnr-frame-expand", "lnr-frame-expand"),
                                            ("lnr-frame-contract", "lnr-frame-contract"),
                                            ("lnr-layers", "lnr-layers"),
                                            ("lnr-funnel", "lnr-funnel"),
                                            ("lnr-text-format", "lnr-text-format"),
                                            ("lnr-text-format-remove", "lnr-text-format-remove"),
                                            ("lnr-text-size", "lnr-text-size"),
                                            ("lnr-bold", "lnr-bold"),
                                            ("lnr-italic", "lnr-italic"),
                                            ("lnr-underline", "lnr-underline"),
                                            ("lnr-strikethrough", "lnr-strikethrough"),
                                            ("lnr-highlight", "lnr-highlight"),
                                            ("lnr-text-align-left", "lnr-text-align-left"),
                                            ("lnr-text-align-center", "lnr-text-align-center"),
                                            ("lnr-text-align-right", "lnr-text-align-right"),
                                            ("lnr-text-align-justify", "lnr-text-align-justify"),
                                            ("lnr-line-spacing", "lnr-line-spacing"),
                                            ("lnr-indent-increase", "lnr-indent-increase"),
                                            ("lnr-indent-decrease", "lnr-indent-decrease"),
                                            ("lnr-pilcrow", "lnr-pilcrow"),
                                            ("lnr-direction-ltr", "lnr-direction-ltr"),
                                            ("lnr-direction-rtl", "lnr-direction-rtl"),
                                            ("lnr-page-break", "lnr-page-break"),
                                            ("lnr-sort-alpha-asc", "lnr-sort-alpha-asc"),
                                            ("lnr-sort-amount-asc", "lnr-sort-amount-asc"),
                                            ("lnr-hand", "lnr-hand"),
                                            ("lnr-pointer-up", "lnr-pointer-up"),
                                            ("lnr-pointer-right", "lnr-pointer-right"),
                                            ("lnr-pointer-down", "lnr-pointer-down"),
                                            ("lnr-pointer-left", "lnr-pointer-left"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "video_banner",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-white", "white"),
                                            ("bg-lightest", "gray"),
                                            ("bg-yellow", "yellow"),
                                            ("bg-transparent", "transparent"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.core.blocks.CharBlock(default="", required=False)),
                                ("description", wagtail.core.blocks.TextBlock(default="")),
                                ("youtube_video_id", wagtail.core.blocks.CharBlock(default="")),
                            ]
                        ),
                    ),
                    (
                        "app_description",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-white", "white"),
                                            ("bg-lightest", "gray"),
                                            ("bg-yellow", "yellow"),
                                            ("bg-transparent", "transparent"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.core.blocks.CharBlock(default="", required=False)),
                                ("description", wagtail.core.blocks.TextBlock(default="")),
                            ]
                        ),
                    ),
                    (
                        "app_features",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-white", "white"),
                                            ("bg-lightest", "gray"),
                                            ("bg-yellow", "yellow"),
                                            ("bg-transparent", "transparent"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.core.blocks.CharBlock(default="", required=False)),
                                ("description", wagtail.core.blocks.TextBlock(default="")),
                            ]
                        ),
                    ),
                    (
                        "app_stores",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-white", "white"),
                                            ("bg-lightest", "gray"),
                                            ("bg-yellow", "yellow"),
                                            ("bg-transparent", "transparent"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.core.blocks.CharBlock(default="", required=False)),
                                ("description", wagtail.core.blocks.TextBlock(default="")),
                            ]
                        ),
                    ),
                    (
                        "newsletter",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-white", "white"),
                                            ("bg-lightest", "gray"),
                                            ("bg-yellow", "yellow"),
                                            ("bg-transparent", "transparent"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.core.blocks.CharBlock(default="", required=False)),
                                ("description", wagtail.core.blocks.TextBlock(default="")),
                            ]
                        ),
                    ),
                    (
                        "press",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-white", "white"),
                                            ("bg-lightest", "gray"),
                                            ("bg-yellow", "yellow"),
                                            ("bg-transparent", "transparent"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.core.blocks.CharBlock(default="", required=False)),
                                ("description", wagtail.core.blocks.TextBlock(default="")),
                            ]
                        ),
                    ),
                    (
                        "stats",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-white", "white"),
                                            ("bg-lightest", "gray"),
                                            ("bg-yellow", "yellow"),
                                            ("bg-transparent", "transparent"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.core.blocks.CharBlock(default="", required=False)),
                                ("description", wagtail.core.blocks.TextBlock(default="")),
                            ]
                        ),
                    ),
                    (
                        "team",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-white", "white"),
                                            ("bg-lightest", "gray"),
                                            ("bg-yellow", "yellow"),
                                            ("bg-transparent", "transparent"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.core.blocks.CharBlock(default="", required=False)),
                                ("description", wagtail.core.blocks.TextBlock(default="")),
                            ]
                        ),
                    ),
                    (
                        "user_quotes",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-white", "white"),
                                            ("bg-lightest", "gray"),
                                            ("bg-yellow", "yellow"),
                                            ("bg-transparent", "transparent"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.core.blocks.CharBlock(default="", required=False)),
                                ("description", wagtail.core.blocks.TextBlock(default="")),
                            ]
                        ),
                    ),
                    (
                        "contact",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-white", "white"),
                                            ("bg-lightest", "gray"),
                                            ("bg-yellow", "yellow"),
                                            ("bg-transparent", "transparent"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.core.blocks.CharBlock(default="", required=False)),
                                ("description", wagtail.core.blocks.TextBlock(default="")),
                            ]
                        ),
                    ),
                    (
                        "icon_features_promo",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "background",
                                    wagtail.core.blocks.ChoiceBlock(
                                        choices=[
                                            ("bg-white", "white"),
                                            ("bg-lightest", "gray"),
                                            ("bg-yellow", "yellow"),
                                            ("bg-transparent", "transparent"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.core.blocks.CharBlock()),
                                ("description", wagtail.core.blocks.TextBlock()),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        )
    ]
