# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4096, verbose_name='Sport Description'),
        ),
    ]
