# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_sport_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='category',
            field=models.CharField(choices=[('basketball', 'Basketball'), ('beach_volleyball', 'Beach Volleyball'), ('bootcamp', 'Bootcamp'), ('boules', 'Boules'), ('fitness', 'Fitness'), ('others', 'Others'), ('skating', 'Skating'), ('soccer', 'Soccer'), ('tennis', 'Tennis')], default='others', help_text='Name of the main category of the sport (e.g. Soccer).', max_length=50, verbose_name='Sport Category'),
        ),
    ]
