# Generated by Django 2.1.2 on 2019-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sports", "0002_auto_20180602_2110")]

    operations = [
        migrations.AlterField(
            model_name="sport",
            name="category",
            field=models.CharField(
                choices=[
                    ("basketball", "Basketball"),
                    ("beach_volleyball", "Beach Volleyball"),
                    ("bootcamp", "Bootcamp"),
                    ("boules", "Boules"),
                    ("fitness", "Fitness"),
                    ("others", "Others"),
                    ("skating", "Skating"),
                    ("soccer", "Soccer"),
                    ("tennis", "Tennis"),
                    ("table_tennis", "Table Tennis"),
                ],
                default="others",
                help_text="Name of the main category of the sport (e.g. Soccer).",
                max_length=50,
                verbose_name="Sport Category",
            ),
        )
    ]
