---
all:
  children:
    app_servers:
      hosts:
        prd.sportyspots.com:
    db_servers:
      hosts:
        prd.sportyspots.com:
  vars:
    env: prd
    celery_workers: 6
    gunicorn_workers: 6
    loglevel: info
    sub_domain: api
...
