---
all:
  children:
    app_servers:
      hosts:
        stg.sportyspots.com:
    db_servers:
      hosts:
        stg.sportyspots.com:
  vars:
    env: stg
    celery_workers: 1
    gunicorn_workers: 1
    loglevel: info
    sub_domain: stg
...
