# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 11:36
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='geocoder',
        ),
        migrations.RemoveField(
            model_name='address',
            name='raw_response',
        ),
        migrations.AddField(
            model_name='address',
            name='geocoder_service',
            field=models.CharField(choices=[('google', 'Google'), ('bing', 'Bing'), ('open_street_maps', 'Open Street Maps'), ('here', 'Here Maps'), ('manual', 'Manual')], default='manual', help_text='Geocoder used to convert raw address into latlong coordinates.', max_length=25, null=True, verbose_name='Geocoder'),
        ),
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='address',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Longtiude'),
        ),
        migrations.AddField(
            model_name='address',
            name='plus_global_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Plus Global Code'),
        ),
        migrations.AddField(
            model_name='address',
            name='plus_local_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Plus Local Code'),
        ),
        migrations.AddField(
            model_name='address',
            name='raw_geocoder_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Raw api response from the geocoder service. e.g. google maps', null=True, verbose_name='Raw Geocoder Response'),
        ),
        migrations.AlterField(
            model_name='address',
            name='formatted_address',
            field=models.CharField(blank=True, help_text='Formatted address returned by the geocoding service', max_length=1024, verbose_name='Formatted Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='address',
            name='raw_address',
            field=models.CharField(help_text='Complete address', max_length=1024, verbose_name='Address'),
        ),
    ]
