# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20180414_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='raw_address',
            field=models.CharField(blank=True, default='', help_text='Complete address', max_length=1024, verbose_name='Address'),
        ),
    ]
