# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-17 11:14
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("locations", "0002_auto_20180602_2110")]

    operations = [
        migrations.AddField(
            model_name="address",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Lat/Lng Point", null=True, srid=4326, verbose_name="Location"
            ),
        )
    ]
