# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20180414_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='location',
        ),
    ]
