# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-17 11:25
from __future__ import unicode_literals

from django.db import migrations

from django.contrib.gis.geos import Point


def set_points(apps, schema_editor):
    Address = apps.get_model("locations", "Address")
    for address in Address.objects.all():
        if address.lat and address.lng:
            address.point = Point(x=float(address.lng), y=float(address.lat), srid=4326)
            address.save()


class Migration(migrations.Migration):

    dependencies = [("locations", "0003_address_point")]

    operations = [migrations.RunPython(set_points)]
