# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('completed', 'Completed'), ('ended', 'Ended'), ('live', 'Live'), ('planned', 'Planned'), ('started', 'Started')], default='planned', max_length=25, verbose_name='Status'),
        ),
    ]
