# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("games", "0002_auto_20180502_0816")]

    operations = [
        migrations.AddField(
            model_name="game",
            name="description",
            field=models.TextField(blank=True, help_text="Description of the game.", verbose_name="Description"),
        )
    ]
