# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20180404_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='invite_mode',
            field=models.CharField(choices=[('approval', 'Approval'), ('invite_only', 'Invite Only'), ('open', 'Open')], default='open', help_text='If the game is open for everyone to join or based on organizers approval or is invite only.', max_length=25, verbose_name='Invite Mode'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='If this game is featured.', verbose_name='Is Featured?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_listed',
            field=models.BooleanField(default=True, help_text='If this game is publicly searchable on SportySpots.', verbose_name='Is Listed?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_shareable',
            field=models.BooleanField(default=True, help_text='If this game shows social sharing buttons.', verbose_name='Is Shareable?'),
        ),
        migrations.AlterField(
            model_name='rsvpstatus',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('attending', 'Attending'), ('checked_in', 'Checked In'), ('declined', 'Declined'), ('interested', 'Interested'), ('invited', 'Invited')], default=None, max_length=25, null=True, verbose_name='Status'),
        ),
    ]
