# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-13 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20180602_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('completed', 'Completed'), ('draft', 'Draft'), ('ended', 'Ended'), ('live', 'Live'), ('planned', 'Planned'), ('started', 'Started')], default='draft', max_length=25, verbose_name='Status'),
        ),
    ]
