# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20180414_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvpstatus',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('accepted', 'Accepted'), ('attending', 'Attending'), ('checked_in', 'Checked In'), ('declined', 'Declined'), ('interested', 'Interested'), ('invited', 'Invited')], default='unknown', max_length=25, null=True, verbose_name='Status'),
        ),
    ]
