# Generated by Django 2.1.3 on 2018-11-17 13:12

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20180613_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=2), django.core.validators.MaxValueValidator(limit_value=50)], verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of the game.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='End time of the game in UTC.', verbose_name='End Time (UTC)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='If this game is featured.', verbose_name='Is featured?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Start time of the game in UTC.', verbose_name='Start Time (UTC)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=django_fsm.FSMField(choices=[('canceled', 'Canceled'), ('completed', 'Completed'), ('draft', 'Draft'), ('ended', 'Ended'), ('live', 'Live'), ('planned', 'Planned'), ('updated', 'Updated'), ('started', 'Started')], default='draft', max_length=25, protected=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='rsvpstatus',
            name='status',
            field=django_fsm.FSMField(choices=[('accepted', 'Accepted'), ('attending', 'Attending'), ('checked_in', 'Checked In'), ('declined', 'Declined'), ('interested', 'Interested'), ('invited', 'Invited'), ('unknown', 'Unknown')], default='unknown', max_length=25, null=True, protected=True, verbose_name='Status'),
        ),
    ]
