# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0005_auto_20180425_1139'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rsvpstatus',
            unique_together=set([('user', 'game')]),
        ),
    ]
