# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20180425_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rsvp_close_time',
            field=models.DateTimeField(help_text='UTC time after that RSVPs will no longer be accepted, though organizers may close RSVPs earlier', verbose_name='RSVP Close Time (UTC)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rsvp_closed',
            field=models.BooleanField(default=False, help_text='Is RSVPing explicitly closed for the game.', verbose_name='RSVP Closed'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rsvp_open_time',
            field=models.DateTimeField(help_text='UTC time before that RSVPs will no longer be accepted, though organizers may close RSVPs earlier', verbose_name='RSVP Open Time (UTC)'),
        ),
    ]
