# Generated by Django 2.1.2 on 2018-12-07 20:23

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20181117_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='End time of the game in UTC.', verbose_name='End Time (UTC)'),
            preserve_default=False,
        ),
    ]
