# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20180425_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_games', to='sports.Sport', verbose_name='Sport'),
        ),
        migrations.AlterField(
            model_name='game',
            name='spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spot_games', to='spots.Spot', verbose_name='Spot'),
        ),
    ]
