# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20180429_1446'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rsvpstatus',
            unique_together=set([]),
        ),
    ]
