# Generated by Django 2.1.2 on 2019-03-09 23:49

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [("games", "0008_auto_20181207_2123")]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("draft", "Draft"),
                    ("ended", "Ended"),
                    ("live", "Live"),
                    ("planned", "Planned"),
                    ("updated", "Updated"),
                    ("started", "Started"),
                ],
                default="draft",
                max_length=25,
                verbose_name="Status",
            ),
        )
    ]
