# Generated by Django 2.1.2 on 2019-03-09 23:56

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [("games", "0009_unprotect_game_status")]

    operations = [
        migrations.AlterField(
            model_name="rsvpstatus",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("accepted", "Accepted"),
                    ("attending", "Attending"),
                    ("checked_in", "Checked In"),
                    ("declined", "Declined"),
                    ("interested", "Interested"),
                    ("invited", "Invited"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=25,
                null=True,
                verbose_name="Status",
            ),
        )
    ]
