---
- name: Debug info
  vars:
    msg: |
      Module Variables ("vars"):
      --------------------------------
      {{ vars | to_nice_json }}

      Environment Variables ("environment"):
      --------------------------------
      {{ environment | to_nice_json }}

      GROUP NAMES Variables ("group_names"):
      --------------------------------
      {{ group_names | to_nice_json }}

      GROUPS Variables ("groups"):
      --------------------------------
      {{ groups | to_nice_json }}

      HOST Variables ("hostvars"):
      --------------------------------
      {{ hostvars | to_nice_json }}

  debug:
    msg: "{{ msg.split('\n') }}"
  when: debug_info
  tags: debug_info

- name: Ensure /var/log/sportyspots exists
  file:
    path: /var/log/sportyspots
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu

- name: Ensure project directories exist for {{ env }}
  become: True
  file:
    path: "/home/ubuntu/sportyspots/{{ env }}"
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu

- name: Ensure project repository exists
  become_user: ubuntu
  git:
    repo: "{{ git_repo }}"
    version: "{{ git_branch }}"
    update: yes
    dest: "/home/ubuntu/sportyspots/{{ env }}"
    key_file: "/home/ubuntu/.ssh/id_rsa"
  register: git_update
  notify:
    - project_changed


- name: Slack alert git update
  slack:
    token: "{{ slack_api_token }}"
    msg: "*github*: deployed branch {{ git_branch }}\n https://github.com/sportyspots/seedorf/compare/{{ git_update.before}}...{{ git_update.after }}"
    channel: "{{ slack_alert_channel }}"
    username: "Ansible [{{ inventory_hostname }}]"
    link_names: 0
    parse: "full"
  tags:
    - deploy

- name: Install dependencies for {{ env }}
  become_user: ubuntu
  command: pipenv install --three --ignore-pipfile
  args:
    chdir: "/home/ubuntu/sportyspots/{{ env }}/"
  notify:
    - restart_supervisor

- name: Copy .env file
  become_user: ubuntu
  copy:
    src: "../../../../.envs/.env.{{ env }}"
    dest: "/home/ubuntu/sportyspots/{{ env }}/.env"
    mode: 0644

- name: Run migrations for {{ env }}
  become_user: ubuntu
  command: pipenv run ./manage.py migrate
  args:
    chdir: "/home/ubuntu/sportyspots/{{ env }}"

- name: Run collectstatic for {{ env }}
  become_user: ubuntu
  command: pipenv run ./manage.py collectstatic --noinput
  args:
    chdir: "/home/ubuntu/sportyspots/{{ env }}"
  notify:
    - flush_redis

- name: Generate supervisor config for {{ env }}
  become_user: root
  template:
    src: supervisor.conf
    dest: "/etc/supervisor/conf.d/sportyspots-{{ env }}.conf"
  notify:
    - restart_supervisor
