---
- name: Ensure project directories exist for {{ deploy.type }}
  become: True
  file:
    path: "/home/ubuntu/sportyspots/{{ deploy.type }}"
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu

- name: Ensure project repository exists
  become_user: ubuntu
  git:
    repo: ssh://git@github.com/sportyspots/seedorf.git
    dest: "/home/ubuntu/sportyspots/{{ deploy.type }}"
    update: yes
    key_file: "/home/ubuntu/.ssh/id_rsa"
  notify:
    - project_changed

- name: Install dependencies for {{ deploy.type }}
  become_user: ubuntu
  command: pipenv install --three --ignore-pipfile
  args:
    chdir: "/home/ubuntu/sportyspots/{{ deploy.type }}/"
  notify:
    - restart_supervisor

- name: Generate deploy config for {{ deploy.type }}
  become_user: ubuntu
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: env, dest: "/home/ubuntu/sportyspots/{{ deploy.type }}/.env" }

- name: Run migrations for {{ deploy.type }}
  become_user: ubuntu
  command: pipenv run ./manage.py migrate
  args:
    chdir: "/home/ubuntu/sportyspots/{{ deploy.type }}"

- name: Run collectstatic for {{ deploy.type }}
  become_user: ubuntu
  command: pipenv run ./manage.py collectstatic --noinput
  args:
    chdir: "/home/ubuntu/sportyspots/{{ deploy.type }}"
  notify:
    - flush_redis

- name: Generate supervisor config for {{ deploy.type }}
  become_user: root
  template:
    src: supervisor.conf
    dest: "/etc/supervisor/conf.d/sportyspots-{{ deploy.type }}.conf"
  notify:
    - restart_supervisor

- name: Flush handlers in case any configs have changed.
  meta: flush_handlers
