---
- name: Add external ppa repositories
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "ppa:chris-lea/redis-server"

- name: Ensure required development tools are installed
  apt:
    name:
      - htop
      - git
      - npm
      - supervisor
      - redis-server
      - python3-redis
      - vim
    state: present

- name: Install Pipenv
  pip:
    name: pipenv
    executable: pip3

- name: Ensure the Redis service is running
  service:
    name: redis-server
    state: started
    enabled: yes

- name: Ensure the supervisor service is running
  service:
    name: supervisor
    state: started
    enabled: yes

- name: Ensure ubuntu user can restart services
  blockinfile:
    dest: /etc/sudoers
    block: |
      Cmnd_Alias    SUPERVISOR = /usr/bin/supervisorctl start *, /usr/bin/supervisorctl stop *, /usr/bin/supervisorctl restart *
      Cmnd_Alias    NGINX = /usr/bin/service nginx reload

      ubuntu ALL=NOPASSWD: SUPERVISOR, NGINX
    validate: "visudo -cf %s"
