---
- name: Add external ppa repositories
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - ppa:chris-lea/redis-server

- name: Ensure required development tools are installed
  apt:
    name:
      - git
      - npm
      - supervisor
      - redis-server
      - python3-redis
      - vim
    state: present

- name: Install Pipenv
  pip:
    name: pipenv
    executable: pip3

#- name: Ensure redis listens on unix socket
#  lineinfile:
#    dest: /etc/redis/redis.conf
#    regexp: '^# unixsocket /var/run/redis/redis.sock'
#    line: 'unixsocket /var/run/redis/redis.sock'
#    backrefs: yes
#  notify: restart_redis
#
#- name: Ensure proper permissions for redis unix socket
#  lineinfile:
#    dest: /etc/redis/redis.conf
#    regexp: '^# unixsocketperm 700'
#    line: 'unixsocketperm 777'
#    backrefs: yes
#  notify: restart_redis

- name: Ensure the Redis service is running
  service:
    name: redis-server
    state: started
    enabled: yes

- name: Ensure the supervisor service is running
  service:
    name: supervisor
    state: started
    enabled: yes

- name: Ensure /var/log/sportyspots exists
  file:
    path: /var/log/sportyspots
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu

- name: Ensure ubuntu user can restart services
  blockinfile:
    dest: /etc/sudoers
    block: |
      Cmnd_Alias    SUPERVISOR = /usr/bin/supervisorctl start *, /usr/bin/supervisorctl stop *, /usr/bin/supervisorctl restart *
      Cmnd_Alias    NGINX = /usr/bin/service nginx reload

      ubuntu ALL=NOPASSWD: SUPERVISOR, NGINX
    validate: 'visudo -cf %s'
...
