---
- name: Ensure ssh host keys are in known hosts
  become_user: ubuntu
  known_hosts:
    path: "/home/ubuntu/.ssh/known_hosts"
    name: "{{ item.key }}"
    key: "{{ item.value }}"
  with_dict: "{{ ssh_known_hosts }}"
...
