---
- include: dev_tools.yml
- include: users.yml
- include: known_hosts.yml
- include: nginx.yml
- include: certbot.yml
- include: deploy_project.yml
#- name: Test secure connection to SSL domain.
#  become: False
#  uri:
#    url: "https://{{ sub_domain }}.{{ domain }}/api/"
#    status_code: 200
#  delegate_to: localhost

