---
- include: ufw.yml

- name: Install Letsencrypt Certbot
  include_role:
    name: geerlingguy.certbot
  vars:
    certbot_admin_email: admin@sportyspots.com
    certbot_create_if_missing: yes
    certbot_create_standalone_stop_services: []
    certbot_certs:
      - domains:
          - "{{ deploy.domain }}"

- name: Install Nginx
  include_role:
    name: geerlingguy.nginx
  vars:
    nginx_remove_default_vhost: true
    nginx_vhosts:
    - listen: "443 ssl http2"
      server_name: "{{ deploy.domain }}"
      root: "/var/www/html"
      index: "index.nginx-debian.html index.php index.html index.htm"
      access_log: "/var/log/nginx/sportyspots-access.log"
      error_log: "/var/log/nginx/sportyspots-error.log"
      filename: "sportyspots.conf"
      state: "present"
      extra_parameters: |
        ssl_certificate     /etc/letsencrypt/live/{{ deploy.domain }}/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/{{ deploy.domain }}/privkey.pem;
        ssl_protocols       TLSv1.1 TLSv1.2;
        ssl_ciphers         HIGH:!aNULL:!MD5;
  notify: restart_nginx
  handlers:
    - include: ../../handlers.yml

- name: Flush handlers in case any configs have changed.
  meta: flush_handlers

- name: Test secure connection to SSL domain.
  uri:
    url: "https://{{ deploy.domain }}/"
    status_code: 200
  delegate_to: localhost
  become: no


...
