# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import seedorf.users.models
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('spots', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Unique Identifier')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NOT_SPECIFIED', 'Not Specified')], default='NOT_SPECIFIED', max_length=25, verbose_name='Gender')),
                ('year_of_birth', models.PositiveSmallIntegerField(blank=True, null=True, validators=[seedorf.users.models.min_value_year_of_birth, seedorf.users.models.max_value_year_of_birth], verbose_name='Year of Birth')),
                ('avatar', models.ImageField(blank=True, upload_to=seedorf.users.models.get_avatar_upload_directory, verbose_name='Avatar Image')),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch')], default='en', max_length=25, verbose_name='Languages')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Amsterdam', verbose_name='Timezone')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Bio')),
                ('sports', models.ManyToManyField(related_name='followers', to='sports.Sport', verbose_name='Favourite Sports')),
                ('spots', models.ManyToManyField(related_name='followers', to='spots.Spot', verbose_name='Favourite Spots')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified At'),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Unique Identifier'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name of User'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Profile'),
        ),
    ]
