# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import seedorf.users.models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch')], default='en', max_length=25, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Amsterdam', verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_birth',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[seedorf.users.models.min_value_year_of_birth, seedorf.users.models.max_value_year_of_birth], verbose_name='Year of Birth'),
        ),
    ]
