# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-18 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0003_auto_20180602_2110")]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="sports",
            field=models.ManyToManyField(
                blank=True,
                related_name="followers",
                to="sports.Sport",
                verbose_name="Favourite Sports",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="spots",
            field=models.ManyToManyField(
                blank=True,
                related_name="followers",
                to="spots.Spot",
                verbose_name="Favourite Spots",
            ),
        ),
    ]
