# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180419_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name of User'),
        ),
    ]
