# Generated by Django 2.1.2 on 2019-03-04 19:57

from django.db import migrations, models
import seedorf.users.models


class Migration(migrations.Migration):

    dependencies = [("users", "0006_magicloginlink")]

    operations = [
        migrations.AlterField(
            model_name="magicloginlink",
            name="token",
            field=models.CharField(
                default=seedorf.users.models.random_string, max_length=32, unique=True, verbose_name="Token"
            ),
        )
    ]
