# Generated by Django 2.1.2 on 2019-03-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0007_alter_magicloginlink")]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("nl", "Dutch"), ("es", "Spanish")],
                default="en",
                max_length=25,
                verbose_name="Languages",
            ),
        )
    ]
