# Generated by Django 2.2b1 on 2019-03-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_language_spanish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicloginlink',
            name='token',
            field=models.TextField(unique=True, verbose_name='Token'),
        ),
    ]
