# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields
import seedorf.spots.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotamenity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='spotamenity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='spotamenity',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified At'),
        ),
        migrations.AddField(
            model_name='spotamenity',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Unique Identifier'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4096, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='homepage_url',
            field=models.URLField(blank=True, help_text='Where can we find out more about this spot ?', max_length=500, verbose_name='Homepage URL'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, upload_to=seedorf.spots.models.get_logo_upload_directory, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='Slug'),
        ),
    ]
