# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_auto_20180414_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='establishment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
