# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_auto_20180414_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spot_address', to='locations.Address'),
        ),
    ]
