# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-14 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_auto_20180414_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Owner'),
        ),
    ]
