# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-15 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_auto_20180414_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotopeningtime',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='spotopeningtime',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='spotopeningtime',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified At'),
        ),
        migrations.AddField(
            model_name='spotopeningtime',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Unique Identifier'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spot', to='locations.Address'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='sports',
            field=models.ManyToManyField(related_name='spots', to='sports.Sport'),
        ),
        migrations.AlterField(
            model_name='spotamenity',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='spots.Spot', verbose_name='Spot Amenity'),
        ),
        migrations.AlterField(
            model_name='spotimage',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spots.Spot'),
        ),
        migrations.AlterField(
            model_name='spotopeningtime',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_times', to='spots.Spot'),
        ),
    ]
