# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0006_auto_20180415_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotopeningtime',
            options={'verbose_name': 'Spot Opening Time', 'verbose_name_plural': 'Spot Opening Times'},
        ),
        migrations.AlterField(
            model_name='spotamenity',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_amenities', to='sports.Sport', verbose_name='Sport Amenity'),
        ),
    ]
