# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_sport_description'),
        ('spots', '0007_auto_20180418_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotimage',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sports.Sport', verbose_name='Spot Images per Sport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotopeningtime',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opening_times', to='sports.Sport', verbose_name='Sport Opening Time'),
            preserve_default=False,
        ),
    ]
