# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0008_auto_20180418_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotamenity',
            options={'verbose_name': 'Spot Amenity per Sport', 'verbose_name_plural': 'Spot Amenities per Sport'},
        ),
        migrations.AlterModelOptions(
            name='spotimage',
            options={'ordering': ('-created_at',), 'verbose_name': 'Spot Image per Sport', 'verbose_name_plural': 'Spot Images per Sport'},
        ),
        migrations.AlterModelOptions(
            name='spotopeningtime',
            options={'verbose_name': 'Spot Opening Time per Sport', 'verbose_name_plural': 'Spot Opening Times per Sport'},
        ),
        migrations.AlterField(
            model_name='spot',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spot', to='locations.Address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='sports',
            field=models.ManyToManyField(related_name='spots', to='sports.Sport', verbose_name='Sports'),
        ),
        migrations.AlterField(
            model_name='spotamenity',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_amenities', to='sports.Sport', verbose_name='Sport'),
        ),
        migrations.AlterField(
            model_name='spotamenity',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='spots.Spot', verbose_name='Spot'),
        ),
        migrations.AlterField(
            model_name='spotimage',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sports.Sport', verbose_name='Sport'),
        ),
        migrations.AlterField(
            model_name='spotimage',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spots.Spot', verbose_name='Spot'),
        ),
        migrations.AlterField(
            model_name='spotopeningtime',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=25),
        ),
        migrations.AlterField(
            model_name='spotopeningtime',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_times', to='sports.Sport', verbose_name='Sport'),
        ),
        migrations.AlterField(
            model_name='spotopeningtime',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_times', to='spots.Spot', verbose_name='Spot'),
        ),
    ]
