# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-19 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0009_auto_20180418_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotamenity',
            options={'verbose_name': 'Spot Amenity', 'verbose_name_plural': 'Spot Amenities'},
        ),
        migrations.AlterModelOptions(
            name='spotimage',
            options={'ordering': ('-created_at',), 'verbose_name': 'Spot Image', 'verbose_name_plural': 'Spot Images'},
        ),
        migrations.AlterModelOptions(
            name='spotopeningtime',
            options={'verbose_name': 'Spot Opening Time', 'verbose_name_plural': 'Spot Opening Times'},
        ),
        migrations.AlterField(
            model_name='spotamenity',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='sports.Sport', verbose_name='Sport'),
        ),
    ]
