# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import seedorf.spots.models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0010_auto_20180419_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotimage',
            name='image',
            field=models.ImageField(upload_to=seedorf.spots.models.get_images_upload_directory),
        ),
        migrations.AlterField(
            model_name='spotimage',
            name='is_flagged',
            field=models.BooleanField(default=False, editable=False, help_text='Is this image marked as offensive/ non-relevant ?'),
        ),
    ]
