# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0011_auto_20180425_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spot', to='locations.Address', verbose_name='Address'),
        ),
    ]
