---
- name: Restart ssh
  service:
    name: ssh
    state: restarted
  listen: restart_ssh

- name: Restart ufw
  service:
    name: ufw
    state: restarted
  listen: restart_ufw

- name: Restart postgresql
  service:
    name: postgresql
    state: restarted
  listen: restart_postgres

- name: Restart supervisor
  service:
    name: supervisor
    state: restarted
  listen:
    - restart_supervisor
    - project_changed

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  listen: restart_nginx

- name: Restart redis
  service:
    name: redis-server
    state: restarted
  listen: restart_redis

- name: Flush redis
  command: redis-cli flushall
  listen:
    - flush_redis
    - project_changed
  # We need to restart supervisor so celery will repopulate redis
  notify: restart_supervisor

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
  listen: restart_rsyslog
