---
- name: Restart supervisor
  service:
    name: supervisor
    state: restarted
  listen:
    - restart_supervisor
    - project_changed

- name: Flush redis
  command: redis-cli flushall
  listen:
    - flush_redis
    - project_changed
  # We need to restart supervisor so celery will repopulate redis
  notify: restart_supervisor

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  listen: restart_nginx
...
